config/routes.rb
GG::Application.routes.draw do
  get "sessions/new"

  resources :users
  resources :sessions, :only => [ :new, :create, :destroy ]
  resources :lists, :only => [ :create, :destroy ] 
  
  match '/home', :to => 'pages#home' 
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => 'pages#home'
  

end

app/models/list.rb
class List < ActiveRecord::Base
	attr_accessible :name
	
	belongs_to :user
	
	validates :name, :presence => true, :length => { :maximum => 140 }
	validates :user_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	attr_accessible :name, :email, :password, :password_confirmation
	
	has_many :lists, :dependent => :destroy
	
	validates :name, :presence => true,
					 :length => { :maximum => 50 }
					 
    email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
	validates :email, :presence => true,
					  :format => { :with => email_regex },
					  :uniqueness => { :case_sensitive => false }
					  
	validates :password, :presence => true, 
						 :confirmation => true,
						 :length => { :within => 6..40 }

	before_save :encrypt_password
	
	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end

	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end
	
	def self.authenticate_with_salt(id, cookie_salt)
		user = find_by_id(id)
		(user && user.salt == cookie_salt) ? user : nil
	end
	
	def feed
		List.where("user_id = ?", id)
	end
	
	private
	
		def encrypt_password
			self.salt = make_salt if new_record?
			self.encrypted_password = encrypt(password)
		end
		
		def encrypt(string)
			secure_hash("#{salt}--#{string}")
		end
		
		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
		end
		
		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

	before_filter :authenticate, :only => [ :create, :destroy ]
	before_filter :authorized_user, :only => :destroy
	
	def create
		@list = current_user.lists.build(params[:list])
		if @list.save
			redirect_to root_path
		else
			@feed_items = []
			render 'pages/home'
		end
	end
	
	def destroy
		@list.destroy
		redirect_back_or root_path
	end
	
	private
	
		def authorized_user
			@list = List.find(params[:id])
			redirect_to root_path unless current_user?(@list.user)
		end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  	if signed_in?
  		@list = List.new
  		@feed_items = current_user.feed
  	end
  	@list = List.new if signed_in?
  end

  def about
  	@title = "About"
  end

  def contact
  	@title = "Contact"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@title = "Sign in"
  end
  
  def create
	user = User.authenticate(params[:session][:email],
							 params[:session][:password])
	if user.nil?
		flash.now[:error] = "Invalid email/password combination"
		@title = "Sign in"
		render 'new'
	else
		sign_in user
		redirect_back_or user
	end
  end
  
  def destroy
  	sign_out
  	redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  
  def new
  	@user = User.new
  	@title = "Sign up"
  end
  
  def show
  	@user = User.find(params[:id])
  	@lists = @user.lists
  	@title = @user.name
  end
  
  def create
  	@user = User.new(params[:user])
  	if @user.save
  		sign_in @user
  		flash[:success] = "Welcome to GroceryGenie #{@user.name}!"
  		redirect_to @user
  	else
  		@title = "Sign up"
  		render 'new'
  	end
  end
  
  def edit
  	@title = "Edit user"
  end
  
  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(params[:user])
  		flash[:success] = "Profile updated."
  		redirect_to @user
  	else
  		@title = "Edit user"
  		render 'edit'
  	end
  end
  
  def index
  	@title = "All users"
  	@users = User.all
  end
  
  def show
  	@user = User.find(params[:id])
  	@title = @user.name
  end
  
  private
  	
  	def correct_user
  		@user = User.find(params[:id])
  		redirect_to root_path unless current_user?(@user)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def title
		base_title = "GroceryGenie"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
	
	def logo
		logo = image_tag("logo.png", :alt => "GroceryAdvance", :class => "logo")
		return logo
	end
	
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent.signed[:remember_token] = [user.id, user.salt]
		self.current_user = user
	end
	
	def sign_out
		cookies.delete(:remember_token)
		self.current_user = nil
	end
	
	def current_user=(user)
		@current_user = user
	end
	
	def current_user
		@current_user ||= user_from_remember_token
	end
	
	def current_user?(user)
		user == current_user
	end
	
	def signed_in?
		!current_user.nil?
	end
	
	def deny_access
		store_location
		redirect_to signin_path, :notice => "Please sign in to access this page."
	end
	
	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		clear_return_to
	end
	
	def authenticate
  		deny_access unless signed_in?
  	end
  		
	private
		
		def user_from_remember_token
			User.authenticate_with_salt(*remember_token)
		end
		
		def remember_token
			cookies.signed[:remember_token] ||= [nil, nil]
		end
		
		def store_location
			session[:return_to] = request.fullpath
		end
		
		def clear_return_to
			session[:return_to] = nil
		end
	

  		
  		
  	
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { :size => 50 })
		gravatar_image_tag(user.email.downcase, :alt => user.name,
												:class => 'gravatar',
												:gravatar => options)
	end
end

app/views/layouts/_footer.html.erb
<header>
	<nav class="round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</header>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<% if signed_in? %>
			<li><%= link_to "Profile", current_user %></li>
			<li><%= link_to "Settings", edit_user_path(current_user) %></li>
			<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
			<% else %>
			<li><%= link_to "Sign in", signin_path %></li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_list.html.erb
<tr>
	<td class="list">
		<span class="name"><%= list.name %></span>
		<span class="timestamp">
			Posted <%= time_ago_in_words(list.created_at) %> ago.
		</span>
	</td>
</tr>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag	'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title> <%= title %> </title>
  		<%= stylesheet_link_tag :all %>
  		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
			<section class="round">
				<% flash.each do |key, value| %>
					<div class="flash <%= key %>"><%= value %></div>
				<% end %>
				<%= yield %>
			</section>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>About GroceryAdvance</h1>
<p>
GroceryAdvance is a technology company dedicated to solving a set of problems
for both grocery purchasers (the consumers) and the retailers who sell them
products.
</p>
<p>
For grocery shoppers, we offer the GroceryGenie smartphone application and 
web application.
</p>
<p>
For retailers, we offer the <a href='http://grocerwords.heroku.com' target='blank'>
GrocerWords</a>, a platform for advertising available specials to GroceryGenie users.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
Hit me up on my cell yo
</p>

app/views/pages/home.html.erb
<% if signed_in? %>
	<table class="front" summary="For signed-in users">
		<tr>
			<td class="main">
				<h1 class="list">Add items below...</h1>
				<%= render 'shared/list_form' %>
				<%= render 'shared/feed' %>
			</td>
			<td class="sidebar round right">
				<%= render 'shared/user_info' %>
			</td>
		</tr>
	</table>
<% else %>
	<h1>GroceryGenie</h1>
	<p>
	Welcome to GroceryGenie. Our goal is to take the hassle out of the grocery
	shopping process and make it easy for you, the consumer, to find deals on the
	products that you buy everyday. 
	</p>
	<p>
	With GroceryGenie, you will be able to:	
	</p>
	
	<ul>
		<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
		<li>Create grocery lists from your browser or smartphone</li>
		<li>Share lists with other shoppers</li>
		<li>View sales on the items you add to your list(s)</li>
		<li>See what specials local merchants are offering</li>
	</ul>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(object.errors.count, "error") %>
		    prohibited this user from being saved:</h2>
		<p>There were problems with the following fields:</p>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
	<table class="lists" summary="User lists">
		<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
	</table>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="list">
    <span class="content"><%= feed_item.name %></span>
    <span class="timestamp">
      Added <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </td>
  <% if current_user?(feed_item.user) %>
  <td>
    <%= link_to "delete", feed_item, :method => :delete,
                                     :confirm => "Are you sure?",
                                     :title => feed_item.name %>
  </td>
  <% end %>
</tr>

app/views/shared/_list_form.html.erb
<%= form_for @list do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit "Add" %>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user_info">
	<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user, :size => 30 %>
	<span class="user_name">
		<%= current_user.name %>'s list
	</span><br />
	<span class="lists">
		<%= pluralize(current_user.lists.count, "item") %>
	</span>
</div>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Update" %>
	</div>
<% end %>

<div>
	<%= gravatar_for @user %>
	<a href="http://gravatar.com/emails" target='blank'>change</a>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<ul class="users">
	<%= @users.each do |user| %>
		<li>
			<%= gravatar_for user, :size => 30 %>
			<%= link_to user.name, user %>
		<li>
	<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirm password" %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Sign up" %>
	</div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
	<tr>
		<td class="main">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %> 
			</h1>

		</td>
		<td class="sidebar round">
			<strong>Name:</strong> <%= @user.name %><br />
			<strong>URL:</strong> <%= link_to user_path(@user), @user %><br />
			<strong>List items:</strong> <%= @user.lists.count %>
		</td>
	</tr>
</table>
			